#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Janick Martinez Esturo"
email = "janick.martinez.esturo@gmail.com"

[ui]
default-command = "log"
diff-editor = ":builtin"
merge-editor = ":builtin"
diff-formatter = ["difft", "--color=always", "--sort-paths", "$left", "$right"]

[aliases]
rebase-all = ["rebase", "-s", "roots(trunk()..mutable())", "-d", "trunk()"]
l = ["log", "-r", "..@ | trunk()"]
lm = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"]
n = ["new"]

[colors]
"diff removed token" = { fg = "bright red", bg = "#400000", underline = false }
"diff added token" = { fg = "bright green", bg = "#003000", underline = false }

[revsets]
bookmark-advance-to = "@-"

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[signing]
backend = "gpg"
key = "A85C4836"
behavior = "own"

[git]
sign-on-push = true

[remotes.origin]
fetch-bookmarks = "~pull-request/*"
